services:
  asterisk:
    build:
      context: build/asterisk
      args:
        DVRTC_VERSION: ${DVRTC_VERSION:-dev}
        DVRTC_SERVICE: asterisk
        VCS_REF: ${VCS_REF:-unknown}
        DVRTC_SOURCE: ${DVRTC_SOURCE:-https://github.com/EnableSecurity/DVRTC}

  rtpengine:
    build:
      context: build/rtpengine
      args:
        DVRTC_VERSION: ${DVRTC_VERSION:-dev}
        DVRTC_SERVICE: rtpengine
        VCS_REF: ${VCS_REF:-unknown}
        DVRTC_SOURCE: ${DVRTC_SOURCE:-https://github.com/EnableSecurity/DVRTC}
        RTPENGINE_VERSION: mr10.5.5.1

  kamailio:
    build:
      context: build/kamailio
      args:
        DVRTC_VERSION: ${DVRTC_VERSION:-dev}
        DVRTC_SERVICE: kamailio
        VCS_REF: ${VCS_REF:-unknown}
        DVRTC_SOURCE: ${DVRTC_SOURCE:-https://github.com/EnableSecurity/DVRTC}
        KAMAILIO_VERSION: 61

  baresip-callgen:
    build:
      context: build/baresip-callgen
      args:
        DVRTC_VERSION: ${DVRTC_VERSION:-dev}
        DVRTC_SERVICE: baresip-callgen
        VCS_REF: ${VCS_REF:-unknown}
        DVRTC_SOURCE: ${DVRTC_SOURCE:-https://github.com/EnableSecurity/DVRTC}

  baresip-callgen-b:
    build:
      context: build/baresip-callgen
      args:
        DVRTC_VERSION: ${DVRTC_VERSION:-dev}
        DVRTC_SERVICE: baresip-callgen
        VCS_REF: ${VCS_REF:-unknown}
        DVRTC_SOURCE: ${DVRTC_SOURCE:-https://github.com/EnableSecurity/DVRTC}

  baresip-callgen-c:
    build:
      context: build/baresip-callgen
      args:
        DVRTC_VERSION: ${DVRTC_VERSION:-dev}
        DVRTC_SERVICE: baresip-callgen
        VCS_REF: ${VCS_REF:-unknown}
        DVRTC_SOURCE: ${DVRTC_SOURCE:-https://github.com/EnableSecurity/DVRTC}

  baresip-digestleak:
    build:
      context: build/baresip-digestleak
      args:
        DVRTC_VERSION: ${DVRTC_VERSION:-dev}
        DVRTC_SERVICE: baresip-digestleak
        VCS_REF: ${VCS_REF:-unknown}
        DVRTC_SOURCE: ${DVRTC_SOURCE:-https://github.com/EnableSecurity/DVRTC}

  nginx:
    build:
      context: build/nginx
      args:
        DVRTC_VERSION: ${DVRTC_VERSION:-dev}
        DVRTC_SERVICE: nginx
        VCS_REF: ${VCS_REF:-unknown}
        DVRTC_SOURCE: ${DVRTC_SOURCE:-https://github.com/EnableSecurity/DVRTC}

  voicemailcleaner:
    build:
      context: build/voicemailcleaner
      args:
        DVRTC_VERSION: ${DVRTC_VERSION:-dev}
        DVRTC_SERVICE: voicemailcleaner
        VCS_REF: ${VCS_REF:-unknown}
        DVRTC_SOURCE: ${DVRTC_SOURCE:-https://github.com/EnableSecurity/DVRTC}

  mysqlclient:
    build:
      context: build/mysqlclient
      args:
        DVRTC_VERSION: ${DVRTC_VERSION:-dev}
        DVRTC_SERVICE: mysqlclient
        VCS_REF: ${VCS_REF:-unknown}
        DVRTC_SOURCE: ${DVRTC_SOURCE:-https://github.com/EnableSecurity/DVRTC}

  dbcleaner:
    build:
      context: build/dbcleaner
      args:
        DVRTC_VERSION: ${DVRTC_VERSION:-dev}
        DVRTC_SERVICE: dbcleaner
        VCS_REF: ${VCS_REF:-unknown}
        DVRTC_SOURCE: ${DVRTC_SOURCE:-https://github.com/EnableSecurity/DVRTC}

  db:
    build:
      context: build/mysql
      args:
        DVRTC_VERSION: ${DVRTC_VERSION:-dev}
        DVRTC_SERVICE: db
        VCS_REF: ${VCS_REF:-unknown}
        DVRTC_SOURCE: ${DVRTC_SOURCE:-https://github.com/EnableSecurity/DVRTC}
